version: v1
description: Nebula Provision Demo

steps:
- name: init-workflow
  image: alpine:latest
  input:
    - echo "Initializing workflow - Nebula Provision Demo"
    - echo "Provisioning a GKE cluster"
- name: provision-gke-with-terraform
  image: projectnebula/terraform:bf8ecb9
  spec:
    vars:
      gcp_region: us-east1
      gcp_location: us-east1-b
      gcp_project: Nebula1
    workspace: nebula-demo
    directory: provision-gke-terraform/infra/
    credentials:
      credentials.json:
        $type: Secret
        name: credentials
    git:
      name: nebula-workflow-examples
      repository: https://github.com/puppetlabs/nebula-workflow-examples.git
  dependsOn:
  - init-workflow
- name: slack-notify
  image: projectnebula/slack-notification:bf8ecb9
  spec:
    apitoken:
      $type: Secret
      name: slack-token
    channel: "#team-se-west"
    message: "If you see this, the Party Llama is wreaking havoc with Nebula"
  dependsOn:
  - provision-gke-with-terraform
